// <auto-generated />
using System;
using MicroservicesReference.Products.Core.Adapters;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroservicesReference.Products.Core.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    [Migration("20250103205320_AddProductsConfig")]
    partial class AddProductsConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MicroservicesReference.Products.Core.Model.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6e6369c3-e7dc-4cb2-8c34-eb40e8d51da2"),
                            Name = "Orange",
                            Price = 1.99m
                        },
                        new
                        {
                            Id = new Guid("d00464c5-950d-45ad-999e-83d947077f37"),
                            Name = "Apple",
                            Price = 2.50m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
