// <auto-generated />
using System;
using MicroservicesReference.Users.Core.Adapters;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroservicesReference.Users.Core.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20250103175320_AddUsersEntityConfig")]
    partial class AddUsersEntityConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MicroservicesReference.Users.Core.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f88c524-1738-4827-be54-aeaf1e2f6de4"),
                            Email = "john@example.com"
                        },
                        new
                        {
                            Id = new Guid("b5e645ad-39aa-4912-8b9e-a2a2ebfa72ee"),
                            Email = "mike@example.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
